<!--
/***************************************
 *** Price Drop Notifier ***
 ***************************************
 *
 * @copyright   Copyright (c) 2015
 * @company     NetAttingo Technologies
 * @package     Netgo_Pricereminder
 * @author 		NetGo
 * @dev			netattingomails@gmail.com
 *
 */
-->
<div style="background: #fef2ed; border: 1px solid #ccc; font-size: 11px; padding: 10px;">
<span>You are successfully unsubscribed for the product, you will no longer get notification mail for the product.</span>
</div>